/**
 * Render the two Homebrew files a release needs, with real versions and hashes.
 *
 *   bun scripts/render-brew-packaging.ts --sums=dist/SHA256SUMS --version=0.1.1
 *   bun scripts/render-brew-packaging.ts … --out=brew-out   # write files too
 *
 * The tap pins an exact version and a sha256 per asset, so every release means
 * editing six hashes across two files by hand — the single most error-prone step
 * in the release runbook, and one where a wrong paste produces a checksum
 * mismatch for users rather than a build failure for us. This reads the release's
 * own SHA256SUMS and prints both files ready to commit.
 *
 * Emits Formula/clidable.rb (the CLI, all four unix targets) and
 * Casks/clidable-desktop.rb (the macOS app, both arches).
 */
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { flag } from "./lib/args";

const root = resolve(import.meta.dir, "..");

const version =
  flag(Bun.argv, "version") ?? (await Bun.file(resolve(root, "package.json")).json()).version;
const sumsPath = resolve(root, flag(Bun.argv, "sums") ?? "dist/SHA256SUMS");
const outFlag = flag(Bun.argv, "out");
const outDir = outFlag ? resolve(root, outFlag) : null;

/** `sha256  filename` (or `sha256  *filename`) → { filename: sha256 } */
export function parseSums(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of text.split("\n")) {
    const m = line.trim().match(/^([0-9a-f]{64})\s+\*?(.+)$/i);
    if (m) out[m[2]!] = m[1]!.toLowerCase();
  }
  return out;
}

/** Look up an asset's hash, failing loudly — a missing entry must never render
 *  as an empty string into a file users install from. */
function need(sums: Record<string, string>, asset: string): string {
  const h = sums[asset];
  if (!h) {
    throw new Error(
      `SHA256SUMS has no entry for "${asset}" — did the release build produce it?\n` +
        `  present: ${Object.keys(sums).join(", ") || "(none)"}`,
    );
  }
  return h;
}

const BASE = "https://github.com/openclide/clidable/releases/download";

export function renderFormula(version: string, sums: Record<string, string>): string {
  const a = (asset: string) => `${BASE}/v${version}/${asset}`;
  return `# typed: false
# frozen_string_literal: true

# The Clidable server/CLI. The download artifact is named \`clidable-server-*\`
# (kept distinct from the \`Clidable_*\` desktop installers in the release
# listing), but the installed command is \`clidable\`. This formula owns the
# bare name so \`brew install openclide/tap/clidable\` means the CLI on every
# platform; the desktop app ships separately as the \`clidable-desktop\` cask.
#
# Generated by scripts/render-brew-packaging.ts — do not hand-edit hashes.
class Clidable < Formula
  desc "GUI for CLI coding agents — server and CLI"
  homepage "https://github.com/openclide/clidable"
  version "${version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${a("clidable-server-darwin-arm64")}"
      sha256 "${need(sums, "clidable-server-darwin-arm64")}"
    end
    on_intel do
      url "${a("clidable-server-darwin-x64")}"
      sha256 "${need(sums, "clidable-server-darwin-x64")}"
    end
  end

  on_linux do
    on_arm do
      url "${a("clidable-server-linux-arm64")}"
      sha256 "${need(sums, "clidable-server-linux-arm64")}"
    end
    on_intel do
      url "${a("clidable-server-linux-x64")}"
      sha256 "${need(sums, "clidable-server-linux-x64")}"
    end
  end

  def install
    # Download artifact is clidable-server-<os>-<arch>; the command is \`clidable\`.
    bin.install Dir["clidable-server-*"].first => "clidable"
  end

  test do
    assert_path_exists bin/"clidable"
    assert_predicate bin/"clidable", :executable?
    # RUN it: existence + the executable bit both pass for a wrong-arch or
    # truncated download, which is precisely the failure a checksum can't catch
    # (a re-uploaded asset hashes fine and still won't exec). \`--version\` prints
    # the bare version and exits 0.
    assert_equal version.to_s, shell_output("#{bin}/clidable --version").strip
  end
end
`;
}

export function renderCask(version: string, sums: Record<string, string>): string {
  // Tauri names the dmg <productName>_<version>_<arch>.dmg, arch being
  // aarch64 / x64 (verified against a real bundle, not inferred).
  const arm = `Clidable_${version}_aarch64.dmg`;
  const intel = `Clidable_${version}_x64.dmg`;
  return `# typed: false
# frozen_string_literal: true

# The Clidable desktop app. Separate from the \`clidable\` formula on purpose:
# that name is the CLI on every platform, and \`brew install …/clidable\` must not
# drag a GUI onto a headless box. Installing both is fine — the app carries its
# own server, and the CLI's \`clidable open\` hands folders to it.
#
# Generated by scripts/render-brew-packaging.ts — do not hand-edit hashes.
cask "clidable-desktop" do
  arch arm: "aarch64", intel: "x64"

  version "${version}"
  sha256 arm:   "${need(sums, arm)}",
         intel: "${need(sums, intel)}"

  url "${BASE}/v#{version}/Clidable_#{version}_#{arch}.dmg",
      verified: "github.com/openclide/clidable/"
  name "Clidable"
  desc "GUI for CLI coding agents"
  homepage "https://github.com/openclide/clidable"

  app "Clidable.app"

  # The app's documented behaviour is window-close-hides / tray-Quit-stops, so it
  # is normally RUNNING. Without this, uninstall deletes Clidable.app out from
  # under a live process, leaving an orphaned server on :7878 and no tray icon
  # left to quit it.
  uninstall quit: "dev.clidable.app"

  # Mirrors the env-paths layout the app actually writes (see
  # docs/configuration.md — data, cache and logs are deliberately separate so
  # OS backup tools treat them differently).
  zap trash: [
    "~/Library/Application Support/Clidable",
    "~/Library/Caches/Clidable",
    "~/Library/Logs/Clidable",
    "~/Library/Preferences/dev.clidable.app.plist",
    "~/Library/Saved Application State/dev.clidable.app.savedState",
    # Tauri's WKWebView writes both of these; without them \`--zap\` leaves the
    # webview's storage behind and doesn't actually return the machine to clean.
    "~/Library/WebKit/dev.clidable.app",
    "~/Library/HTTPStorages/dev.clidable.app",
  ]
end
`;
}

if (import.meta.main) {
  const sums = parseSums(await Bun.file(sumsPath).text());

  // preflight permits numeric pre-releases (v0.1.0-1). npm routes those to a
  // `next` dist-tag, but brew has no such concept here: the formula owns the
  // bare `clidable` name, so committing a pre-release version into it would
  // serve it to every `brew install`/`brew upgrade`. Render nothing and say so.
  if (version.includes("-")) {
    console.error(
      `refusing to render Homebrew packaging for pre-release version "${version}".\n` +
        `  Formula/clidable.rb owns the bare \`clidable\` name — a pre-release there\n` +
        `  reaches everyone on \`brew upgrade\`. Ship pre-releases via npm's \`next\`\n` +
        `  tag and the GitHub release assets, and bump the tap on a final version.`,
    );
    process.exit(0); // not a build failure: the release itself is fine
  }

  // The formula is required: its four server binaries are what gates the whole
  // release, so a missing one must fail loudly.
  const formula = renderFormula(version, sums);

  // The cask is NOT. A flaked desktop leg leaves no dmg, and the release job is
  // deliberately built to draft anyway ("one NSIS flake would suppress the
  // entire release") — so throwing here would abort the job and take the draft,
  // and the very step that reports the flake, down with it. Warn and skip.
  let cask: string | null = null;
  try {
    cask = renderCask(version, sums);
  } catch (e) {
    console.error(
      `! skipping the cask: ${(e as Error).message}\n` +
        `  (expected when a desktop leg failed — re-run it, then re-run this job)`,
    );
  }

  if (outDir) {
    await mkdir(resolve(outDir, "Formula"), { recursive: true });
    await mkdir(resolve(outDir, "Casks"), { recursive: true });
    await Bun.write(resolve(outDir, "Formula/clidable.rb"), formula);
    console.log(`✓ wrote ${outDir}/Formula/clidable.rb`);
    if (cask) {
      await Bun.write(resolve(outDir, "Casks/clidable-desktop.rb"), cask);
      console.log(`✓ wrote ${outDir}/Casks/clidable-desktop.rb`);
    }
  } else {
    console.log(`===== Formula/clidable.rb =====\n${formula}`);
    if (cask) console.log(`===== Casks/clidable-desktop.rb =====\n${cask}`);
  }
}
