/**
 * Render the two Homebrew files a release needs, with real versions and hashes.
 *
 *   bun scripts/render-brew-packaging.ts --sums=dist/SHA256SUMS --version=0.1.1
 *   bun scripts/render-brew-packaging.ts … --out=brew-out   # write files too
 *
 * The tap pins an exact version and a sha256 per asset, so every release means
 * editing six hashes across two files by hand — the single most error-prone step
 * in the release runbook, and one where a wrong paste produces a checksum
 * mismatch for users rather than a build failure for us. This reads the release's
 * own SHA256SUMS and prints both files ready to commit.
 *
 * Emits Formula/clidable.rb (the CLI, all four unix targets) and
 * Casks/clidable-desktop.rb (the macOS app, both arches).
 */
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const arg = (n: string): string | undefined =>
  Bun.argv.find((a) => a.startsWith(`--${n}=`))?.slice(n.length + 3);

const version = arg("version") ?? (await Bun.file(resolve(root, "package.json")).json()).version;
const sumsPath = resolve(root, arg("sums") ?? "dist/SHA256SUMS");
const outDir = arg("out") ? resolve(root, arg("out")!) : null;

/** `sha256  filename` (or `sha256  *filename`) → { filename: sha256 } */
export function parseSums(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of text.split("\n")) {
    const m = line.trim().match(/^([0-9a-f]{64})\s+\*?(.+)$/i);
    if (m) out[m[2]!] = m[1]!.toLowerCase();
  }
  return out;
}

/** Look up an asset's hash, failing loudly — a missing entry must never render
 *  as an empty string into a file users install from. */
function need(sums: Record<string, string>, asset: string): string {
  const h = sums[asset];
  if (!h) {
    throw new Error(
      `SHA256SUMS has no entry for "${asset}" — did the release build produce it?\n` +
        `  present: ${Object.keys(sums).join(", ") || "(none)"}`,
    );
  }
  return h;
}

const BASE = "https://github.com/openclide/clidable/releases/download";

export function renderFormula(version: string, sums: Record<string, string>): string {
  const a = (asset: string) => `${BASE}/v${version}/${asset}`;
  return `# typed: false
# frozen_string_literal: true

# The Clidable server/CLI. The download artifact is named \`clidable-server-*\`
# (kept distinct from the \`Clidable_*\` desktop installers in the release
# listing), but the installed command is \`clidable\`. This formula owns the
# bare name so \`brew install openclide/tap/clidable\` means the CLI on every
# platform; the desktop app ships separately as the \`clidable-desktop\` cask.
#
# Generated by scripts/render-brew-packaging.ts — do not hand-edit hashes.
class Clidable < Formula
  desc "GUI for CLI coding agents — server and CLI"
  homepage "https://github.com/openclide/clidable"
  version "${version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${a("clidable-server-darwin-arm64")}"
      sha256 "${need(sums, "clidable-server-darwin-arm64")}"
    end
    on_intel do
      url "${a("clidable-server-darwin-x64")}"
      sha256 "${need(sums, "clidable-server-darwin-x64")}"
    end
  end

  on_linux do
    on_arm do
      url "${a("clidable-server-linux-arm64")}"
      sha256 "${need(sums, "clidable-server-linux-arm64")}"
    end
    on_intel do
      url "${a("clidable-server-linux-x64")}"
      sha256 "${need(sums, "clidable-server-linux-x64")}"
    end
  end

  def install
    # Download artifact is clidable-server-<os>-<arch>; the command is \`clidable\`.
    bin.install Dir["clidable-server-*"].first => "clidable"
  end

  test do
    assert_path_exists bin/"clidable"
    assert_predicate bin/"clidable", :executable?
  end
end
`;
}

export function renderCask(version: string, sums: Record<string, string>): string {
  // Tauri names the dmg <productName>_<version>_<arch>.dmg, arch being
  // aarch64 / x64 (verified against a real bundle, not inferred).
  const arm = `Clidable_${version}_aarch64.dmg`;
  const intel = `Clidable_${version}_x64.dmg`;
  return `# typed: false
# frozen_string_literal: true

# The Clidable desktop app. Separate from the \`clidable\` formula on purpose:
# that name is the CLI on every platform, and \`brew install …/clidable\` must not
# drag a GUI onto a headless box. Installing both is fine — the app carries its
# own server, and the CLI's \`clidable open\` hands folders to it.
#
# Generated by scripts/render-brew-packaging.ts — do not hand-edit hashes.
cask "clidable-desktop" do
  arch arm: "aarch64", intel: "x64"

  version "${version}"
  sha256 arm:   "${need(sums, arm)}",
         intel: "${need(sums, intel)}"

  url "${BASE}/v#{version}/Clidable_#{version}_#{arch}.dmg",
      verified: "github.com/openclide/clidable/"
  name "Clidable"
  desc "GUI for CLI coding agents"
  homepage "https://github.com/openclide/clidable"

  app "Clidable.app"

  # Mirrors the env-paths layout the app actually writes (see
  # docs/configuration.md — data, cache and logs are deliberately separate so
  # OS backup tools treat them differently).
  zap trash: [
    "~/Library/Application Support/Clidable",
    "~/Library/Caches/Clidable",
    "~/Library/Logs/Clidable",
    "~/Library/Preferences/dev.clidable.app.plist",
    "~/Library/Saved Application State/dev.clidable.app.savedState",
  ]
end
`;
}

if (import.meta.main) {
  const sums = parseSums(await Bun.file(sumsPath).text());
  const formula = renderFormula(version, sums);
  const cask = renderCask(version, sums);

  if (outDir) {
    await mkdir(resolve(outDir, "Formula"), { recursive: true });
    await mkdir(resolve(outDir, "Casks"), { recursive: true });
    await Bun.write(resolve(outDir, "Formula/clidable.rb"), formula);
    await Bun.write(resolve(outDir, "Casks/clidable-desktop.rb"), cask);
    console.log(`✓ wrote ${outDir}/Formula/clidable.rb and ${outDir}/Casks/clidable-desktop.rb`);
  } else {
    console.log(`===== Formula/clidable.rb =====\n${formula}`);
    console.log(`===== Casks/clidable-desktop.rb =====\n${cask}`);
  }
}
